### ISSUE TITLE
Error in peragro-at

### ISSUE THREAD

**Issue by divamgupta** [peragro/peragro-at#17]
I tried running :
pt a /tmp/peragro peragro-test-files/mesh/blender/cube1.blend

It gave the following error:
```
usage: pt [-h] [-v] [-q] {a,i,t} ...
pt: error: unrecognized arguments: peragro-test-files/mesh/blender/cube1.blend
```

Then I ran:
 pt a peragro-test-files/mesh/blender/cube1.blend

It gave the following error.
```
Traceback (most recent call last):
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/analyzer.py", line 130, in analyze_file
    file_descr = self.analyzers[mimetype].plugin_object.analyze(an_uri)
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/analyzers/mesh/analyzerblend.py", line 47, in analyze
    data = str(stdoutdata).split('-**-')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/divam/Desktop/Peragro/env/bin/pt", line 9, in <module>
    load_entry_point('damn-at==heads-master', 'console_scripts', 'pt')()
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/cli.py", line 335, in main
    args.func(args)
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/cli.py", line 105, in <lambda>
    args.store
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/cli.py", line 82, in analyze
    descr = analyzer.analyze_file(path)
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/analyzer.py", line 137, in analyze_file
    raise AnalyzerException("E: Failed to analyze %s because of %s" % (an_uri, str(ex)))
damn_at.analyzer.AnalyzerException: 'E: Failed to analyze peragro-test-files/mesh/blender/cube1.blend because of list index out of range

```

This is due to an error thrown by the blender wrapper in the stderr

```
Traceback (most recent call last):
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/analyzers/mesh/b-script-analyzerblend.py", line 13, in <module>
    import metadata
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/analyzers/mesh/metadata.py", line 1, in <module>
    from damn_at.metadata import MetaDataExtractor
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/__init__.py", line 24, in <module>
    from damn_at.analyzer import Analyzer  # pylint: disable=W0611
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/analyzer.py", line 14, in <module>
    from damn_at.pluginmanager import DAMNPluginManagerSingleton
  File "/home/divam/Desktop/Peragro/peragro-at/src/damn_at/pluginmanager.py", line 12, in <module>
    from yapsy.IPlugin import IPlugin
ImportError: No module named 'yapsy'


```

But yapsy is installed and it is found  if I import it without blender.
I followed the instructions exactly and im running Ubuntu 14.04 LTS

**Comment by sueastside** [comment]
The syntax is slightly different now, 'pt a peragro-test-files/mesh/blender/cube1.blend' I updated the readme.

**Comment by sueastside** [comment]
As for the second error, peragro-at needs to be installed in python3 as well so blender can use it.

outside your virtual env:
cd peragro-at
sudo python3 setup.py develop

Updated the readme.
