### ISSUE TITLE
python 2/3 support

### ISSUE THREAD

**Issue by botanicvelious** [peragro/peragro-at#35]
there seems to be issues running peragro-at on python 3 following the instructions

**Comment by linganesan** [comment]
yup!

When I try to run ' pt a peragro-test-files/mesh/blender/cube1.blend' through python3, I get this error...

`Traceback (most recent call last):
  File "/usr/bin/pt", line 11, in <module>
    load_entry_point('damn-at===0.0.0-development', 'console_scripts', 'pt')()
  File "/usr/lib/python3.5/site-packages/damn_at-0.0.0_development-py3.5.egg/damn_at/cli.py", line 330, in main
    parser = create_argparse()
  File "/usr/lib/python3.5/site-packages/damn_at-0.0.0_development-py3.5.egg/damn_at/cli.py", line 317, in create_argparse
    plugin = entrypoint.load(require=False)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/damn_index-0.1-py3.5.egg/damn_index/__init__.py", line 4, in <module>
    from damnsearch import DAMNSearch
ImportError: No module named 'damnsearch' `

but when I run the same analyze instruction through python2, I get this error...

`Traceback (most recent call last):
  File "/usr/bin/pt", line 11, in <module>
    load_entry_point('damn-at===heads-master', 'console_scripts', 'pt')()
  File "/usr/lib/python2.7/site-packages/damn_at-heads_master-py2.7.egg/damn_at/cli.py", line 349, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/damn_at-heads_master-py2.7.egg/damn_at/cli.py", line 105, in <lambda>
    args.store
  File "/usr/lib/python2.7/site-packages/damn_at-heads_master-py2.7.egg/damn_at/cli.py", line 82, in analyze
    descr = analyzer.analyze_file(path)
  File "/usr/lib/python2.7/site-packages/damn_at-heads_master-py2.7.egg/damn_at/analyzer.py", line 167, in analyze_file
    raise AnalyzerUnknownTypeException("E: Analyzer: No analyzer for %s (file: %s)" % (mimetype, an_uri))
damn_at.analyzer.AnalyzerUnknownTypeException: 'E: Analyzer: No analyzer for application/x-blender (file: peragro-test-files/mesh/blender/cube1.blend)'
`
What's going on?

**Comment by linganesan** [comment]
Hey! did anyone get any issues related on importing damnsearch while running through python 3?

**Comment by botanicvelious** [comment]
try latest version should work
